# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'polarizer_sweep.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1868, 1103)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("QWidget#Form{\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QWidget#mainwidget{\n"
"    background-color: rgba(239, 244, 249, 0);\n"
"    border-radius:10px;\n"
"}\n"
"QFrame#mainframe{\n"
"    background-color: rgba(239, 244, 249, 255);\n"
"    border-radius:10px;\n"
"}\n"
"QGroupBox{\n"
"    border-width: 2px;\n"
"    \n"
"    font: 25 9pt \"Microsoft YaHei UI Light\";\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 2px;\n"
"    border: 1px groove gray;\n"
"    font: 63 9pt \"Nunito Sans SemiBold\";\n"
"}\n"
"QTabWidget{\n"
"    font: 63 9pt \"Nunito Sans SemiBold\";\n"
"}\n"
"QLabel{\n"
"    font: 9pt \"Microsoft YaHei UI\";\n"
"}\n"
"QComboBox{\n"
"    \n"
"    font: 9pt \"Menlo for Powerline\";\n"
"}\n"
"")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.mainwidget = QtWidgets.QWidget(Form)
        self.mainwidget.setStyleSheet("")
        self.mainwidget.setObjectName("mainwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.mainwidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.mainframe = QtWidgets.QFrame(self.mainwidget)
        self.mainframe.setStyleSheet("")
        self.mainframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe.setObjectName("mainframe")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainframe)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.mainframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 40))
        self.frame.setBaseSize(QtCore.QSize(0, 0))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(5, 1, 1, 1)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/my_icons/images/icons/window_title_icon.png"))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.min_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_btn.sizePolicy().hasHeightForWidth())
        self.min_btn.setSizePolicy(sizePolicy)
        self.min_btn.setMaximumSize(QtCore.QSize(60, 30))
        self.min_btn.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    border-radius: 2px;\n"
"    background-color: rgba(239, 244, 249, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(160, 160, 160,100);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: transparent;\n"
"}\n"
"")
        self.min_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/my_icons/images/icons/min.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.min_btn.setIcon(icon)
        self.min_btn.setObjectName("min_btn")
        self.horizontalLayout_2.addWidget(self.min_btn)
        self.max_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_btn.sizePolicy().hasHeightForWidth())
        self.max_btn.setSizePolicy(sizePolicy)
        self.max_btn.setMaximumSize(QtCore.QSize(60, 30))
        self.max_btn.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    border-radius: 2px;\n"
"    background-color: rgba(239, 244, 249, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(160, 160, 160,100);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: transparent;\n"
"}")
        self.max_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/my_icons/images/icons/max.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.max_btn.setIcon(icon1)
        self.max_btn.setIconSize(QtCore.QSize(20, 20))
        self.max_btn.setObjectName("max_btn")
        self.horizontalLayout_2.addWidget(self.max_btn)
        self.close_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_btn.sizePolicy().hasHeightForWidth())
        self.close_btn.setSizePolicy(sizePolicy)
        self.close_btn.setMaximumSize(QtCore.QSize(60, 30))
        self.close_btn.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    border-radius: 2px;\n"
"    background-color: rgba(239, 244, 249, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(196, 43, 28,200);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: transparent;\n"
"}")
        self.close_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/my_icons/images/icons/close_btn.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon2)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_2.addWidget(self.close_btn)
        self.horizontalLayout_2.setStretch(4, 3)
        self.horizontalLayout_2.setStretch(5, 3)
        self.horizontalLayout_2.setStretch(6, 3)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.mainframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgb(160, 160, 160,100);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: transparent;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_2)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 571, 601))
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius:10px;\n"
"    background-color: rgb(190, 190, 190,50);\n"
"}\n"
"\n"
"")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.rot_a = QtWidgets.QWidget()
        self.rot_a.setObjectName("rot_a")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.rot_a)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.rot_a)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.serial_cbox = QtWidgets.QComboBox(self.rot_a)
        self.serial_cbox.setObjectName("serial_cbox")
        self.serial_cbox.addItem("")
        self.serial_cbox.addItem("")
        self.horizontalLayout.addWidget(self.serial_cbox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.connect_btn = QtWidgets.QPushButton(self.rot_a)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/my_icons/images/icons/connect.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.connect_btn.setIcon(icon3)
        self.connect_btn.setObjectName("connect_btn")
        self.horizontalLayout.addWidget(self.connect_btn)
        self.disconnect_btn = QtWidgets.QPushButton(self.rot_a)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/my_icons/images/icons/disconnect.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.disconnect_btn.setIcon(icon4)
        self.disconnect_btn.setObjectName("disconnect_btn")
        self.horizontalLayout.addWidget(self.disconnect_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.groupBox = QtWidgets.QGroupBox(self.rot_a)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.position_view = QtWidgets.QLCDNumber(self.groupBox)
        self.position_view.setDigitCount(8)
        self.position_view.setMode(QtWidgets.QLCDNumber.Dec)
        self.position_view.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.position_view.setObjectName("position_view")
        self.verticalLayout_7.addWidget(self.position_view)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.rotator_a_velocity_spbx = QtWidgets.QSpinBox(self.groupBox)
        self.rotator_a_velocity_spbx.setProperty("value", 10)
        self.rotator_a_velocity_spbx.setObjectName("rotator_a_velocity_spbx")
        self.horizontalLayout_8.addWidget(self.rotator_a_velocity_spbx)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.rotator_a_acceleration_spbx = QtWidgets.QSpinBox(self.groupBox)
        self.rotator_a_acceleration_spbx.setProperty("value", 10)
        self.rotator_a_acceleration_spbx.setObjectName("rotator_a_acceleration_spbx")
        self.horizontalLayout_8.addWidget(self.rotator_a_acceleration_spbx)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.rotator_a_step_spbx = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.rotator_a_step_spbx.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rotator_a_step_spbx.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.rotator_a_step_spbx.setProperty("value", 5.0)
        self.rotator_a_step_spbx.setObjectName("rotator_a_step_spbx")
        self.horizontalLayout_8.addWidget(self.rotator_a_step_spbx)
        self.rotator_a_set_btn = QtWidgets.QPushButton(self.groupBox)
        self.rotator_a_set_btn.setObjectName("rotator_a_set_btn")
        self.horizontalLayout_8.addWidget(self.rotator_a_set_btn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.verticalLayout_7.setStretch(0, 3)
        self.verticalLayout_7.setStretch(1, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rotator_a_cont_rdbtn = QtWidgets.QRadioButton(self.groupBox)
        self.rotator_a_cont_rdbtn.setChecked(True)
        self.rotator_a_cont_rdbtn.setObjectName("rotator_a_cont_rdbtn")
        self.verticalLayout_2.addWidget(self.rotator_a_cont_rdbtn)
        self.rotator_a_stp_rdbtn = QtWidgets.QRadioButton(self.groupBox)
        self.rotator_a_stp_rdbtn.setObjectName("rotator_a_stp_rdbtn")
        self.verticalLayout_2.addWidget(self.rotator_a_stp_rdbtn)
        self.rotator_a_forward_btn = QtWidgets.QPushButton(self.groupBox)
        self.rotator_a_forward_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/my_icons/images/icons/up_arrow.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotator_a_forward_btn.setIcon(icon5)
        self.rotator_a_forward_btn.setIconSize(QtCore.QSize(50, 50))
        self.rotator_a_forward_btn.setFlat(False)
        self.rotator_a_forward_btn.setObjectName("rotator_a_forward_btn")
        self.verticalLayout_2.addWidget(self.rotator_a_forward_btn)
        self.rotator_a_backward_btn = QtWidgets.QPushButton(self.groupBox)
        self.rotator_a_backward_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/my_icons/images/icons/down_arrow.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotator_a_backward_btn.setIcon(icon6)
        self.rotator_a_backward_btn.setIconSize(QtCore.QSize(50, 50))
        self.rotator_a_backward_btn.setFlat(False)
        self.rotator_a_backward_btn.setObjectName("rotator_a_backward_btn")
        self.verticalLayout_2.addWidget(self.rotator_a_backward_btn)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 2)
        self.verticalLayout_2.setStretch(3, 2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rot_a_ledit = QtWidgets.QLineEdit(self.rot_a)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rot_a_ledit.sizePolicy().hasHeightForWidth())
        self.rot_a_ledit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.rot_a_ledit.setFont(font)
        self.rot_a_ledit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rot_a_ledit.setObjectName("rot_a_ledit")
        self.horizontalLayout_3.addWidget(self.rot_a_ledit)
        self.move_tbtn = QtWidgets.QToolButton(self.rot_a)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/my_icons/images/icons/move.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.move_tbtn.setIcon(icon7)
        self.move_tbtn.setIconSize(QtCore.QSize(40, 40))
        self.move_tbtn.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.move_tbtn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.move_tbtn.setArrowType(QtCore.Qt.NoArrow)
        self.move_tbtn.setObjectName("move_tbtn")
        self.horizontalLayout_3.addWidget(self.move_tbtn)
        self.home_tbtn = QtWidgets.QToolButton(self.rot_a)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/my_icons/images/icons/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_tbtn.setIcon(icon8)
        self.home_tbtn.setIconSize(QtCore.QSize(40, 40))
        self.home_tbtn.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.home_tbtn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.home_tbtn.setArrowType(QtCore.Qt.NoArrow)
        self.home_tbtn.setObjectName("home_tbtn")
        self.horizontalLayout_3.addWidget(self.home_tbtn)
        self.stop_tbtn = QtWidgets.QToolButton(self.rot_a)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/my_icons/images/icons/stop_rotate.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_tbtn.setIcon(icon9)
        self.stop_tbtn.setIconSize(QtCore.QSize(40, 40))
        self.stop_tbtn.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.stop_tbtn.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.stop_tbtn.setArrowType(QtCore.Qt.NoArrow)
        self.stop_tbtn.setObjectName("stop_tbtn")
        self.horizontalLayout_3.addWidget(self.stop_tbtn)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.groupBox_7 = QtWidgets.QGroupBox(self.rot_a)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.rot_a_scroll = QtWidgets.QScrollArea(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rot_a_scroll.sizePolicy().hasHeightForWidth())
        self.rot_a_scroll.setSizePolicy(sizePolicy)
        self.rot_a_scroll.setWidgetResizable(True)
        self.rot_a_scroll.setObjectName("rot_a_scroll")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 535, 85))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.rot_a_msg = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.rot_a_msg.setText("")
        self.rot_a_msg.setObjectName("rot_a_msg")
        self.verticalLayout_20.addWidget(self.rot_a_msg)
        self.rot_a_scroll.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_4.addWidget(self.rot_a_scroll, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_7)
        self.groupBox_2 = QtWidgets.QGroupBox(self.rot_a)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.rotator_a_startpos_spbx = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.rotator_a_startpos_spbx.setMaximum(360.0)
        self.rotator_a_startpos_spbx.setObjectName("rotator_a_startpos_spbx")
        self.gridLayout.addWidget(self.rotator_a_startpos_spbx, 0, 1, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 3, 1, 1)
        self.rotator_a_stoppos_spbx = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.rotator_a_stoppos_spbx.setMaximum(360.0)
        self.rotator_a_stoppos_spbx.setObjectName("rotator_a_stoppos_spbx")
        self.gridLayout.addWidget(self.rotator_a_stoppos_spbx, 0, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 5, 1, 1)
        self.rotator_a_sweepstep_spbx = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.rotator_a_sweepstep_spbx.setObjectName("rotator_a_sweepstep_spbx")
        self.gridLayout.addWidget(self.rotator_a_sweepstep_spbx, 0, 6, 1, 1)
        self.rotator_a_frames_spbx = QtWidgets.QLabel(self.groupBox_2)
        self.rotator_a_frames_spbx.setObjectName("rotator_a_frames_spbx")
        self.gridLayout.addWidget(self.rotator_a_frames_spbx, 0, 7, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 0, 8, 1, 1)
        self.rotato_a_progressbar = QtWidgets.QProgressBar(self.groupBox_2)
        self.rotato_a_progressbar.setStyleSheet("QProgressBar {\n"
"    border: 2px solid grey;\n"
"    background-color: #f0f0f0;\n"
"    padding: 1px;\n"
"    height: 16px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #00bcd4;\n"
"    width: 10px;\n"
"}")
        self.rotato_a_progressbar.setProperty("value", 0)
        self.rotato_a_progressbar.setAlignment(QtCore.Qt.AlignCenter)
        self.rotato_a_progressbar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.rotato_a_progressbar.setObjectName("rotato_a_progressbar")
        self.gridLayout.addWidget(self.rotato_a_progressbar, 1, 2, 1, 7)
        self.rotator_a_sweep_start_btn = QtWidgets.QPushButton(self.groupBox_2)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/my_icons/images/icons/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotator_a_sweep_start_btn.setIcon(icon10)
        self.rotator_a_sweep_start_btn.setIconSize(QtCore.QSize(20, 30))
        self.rotator_a_sweep_start_btn.setObjectName("rotator_a_sweep_start_btn")
        self.gridLayout.addWidget(self.rotator_a_sweep_start_btn, 1, 0, 1, 2)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.rot_a, "")
        self.rot_b = QtWidgets.QWidget()
        self.rot_b.setObjectName("rot_b")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.rot_b)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget.addTab(self.rot_b, "")
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout_5.addWidget(self.mainframe)
        self.verticalLayout_19.addWidget(self.mainwidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Rotater Automation"))
        self.label_6.setText(_translate("Form", "----Version 1.0 --By Qin Yuanhao"))
        self.label_3.setText(_translate("Form", "Serial Number:"))
        self.serial_cbox.setItemText(0, _translate("Form", "S/N 55354044"))
        self.serial_cbox.setItemText(1, _translate("Form", "S/N 55342484"))
        self.connect_btn.setText(_translate("Form", "Connect"))
        self.disconnect_btn.setText(_translate("Form", "Disconnect"))
        self.groupBox.setTitle(_translate("Form", "Drive"))
        self.label_5.setText(_translate("Form", "Velocity: "))
        self.label_7.setText(_translate("Form", "Acceleration: "))
        self.label_8.setText(_translate("Form", "Step:"))
        self.rotator_a_set_btn.setText(_translate("Form", "Set"))
        self.rotator_a_cont_rdbtn.setText(_translate("Form", "Continuous"))
        self.rotator_a_stp_rdbtn.setText(_translate("Form", "Stepping"))
        self.rot_a_ledit.setPlaceholderText(_translate("Form", "Input Degrees"))
        self.move_tbtn.setText(_translate("Form", " Move "))
        self.home_tbtn.setText(_translate("Form", " Home "))
        self.stop_tbtn.setText(_translate("Form", " Stop "))
        self.groupBox_7.setTitle(_translate("Form", "K10CR1/M (Rotator A) Setup Info"))
        self.groupBox_2.setTitle(_translate("Form", "Polarization Sweep"))
        self.label_4.setText(_translate("Form", "StartPos:"))
        self.label_9.setText(_translate("Form", "StopPos:"))
        self.label_10.setText(_translate("Form", "Step:"))
        self.rotator_a_frames_spbx.setText(_translate("Form", "Frames:"))
        self.rotator_a_sweep_start_btn.setText(_translate("Form", "Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rot_a), _translate("Form", "Polarization"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rot_b), _translate("Form", "Power"))
import resources_rc
